### ISSUE TITLE
Create basic homepage

### ISSUE THREAD

**Issue by Peiblos** [Peiblos/perbarn-works#2]
Create homepage.

Example links:
https://mimoreformas.es/
https://www.qbconstructora.es/

**Comment by Peiblos** [comment]
@Zenidd I will update this ticket with any news.

**Comment by Zenidd** [comment]
Hey @Peiblos any updates on this?

**Comment by Peiblos** [comment]
This is the initial structure design

From desktop:

![Image](https://github.com/user-attachments/assets/c9b22a0e-0a06-4aaf-988c-e46ed1b261b5)

![Image](https://github.com/user-attachments/assets/8df37c76-3896-46e6-a21f-013883d7a495)

![Image](https://github.com/user-attachments/assets/b0539aa0-89ae-4d00-953e-cd2798a105f8)

![Image](https://github.com/user-attachments/assets/09ccf834-8629-4652-98d9-1b5032a48bc8)

 To mobile-tablet:

![Image](https://github.com/user-attachments/assets/01c438c9-776e-4fda-9189-45d577311fe8)

![Image](https://github.com/user-attachments/assets/448811ff-8282-429b-85fa-cdd73b90a75a)

made in html and css.

**Comment by Zenidd** [comment]
Great work @Peiblos 🦾🦾🦾

Now lets move the design to the vite project and commit the changes... that way I can connect the repo to Amazon Web Services where we will have the online develop environment.

Im going to check for the colour palette and i'm going to start getting some pictures that you can use in the carousel.

As a suggestion there are many libraries to implement a carousel that offer nice features.

As the site name you can use Pebarns works

As I said good job and keep it up!

**Comment by Zenidd** [comment]
The ideal way to implement a new feature should be the following

 
- Create a new branch based on the current status
- You implement the changes on that branch
- Once you are happy with the changes, you push the branch to github 
- Create a pull request and link the issue/ticket

**Comment by Peiblos** [comment]
Hey Mr. @Zenidd

Which are the different links in the navbar and sections?

**Comment by Zenidd** [comment]
Hey @Peiblos ,

![Image](https://github.com/user-attachments/assets/9994e59f-63a0-4721-869b-3f8f3a4a8e91)

Lets start with the ones in the example above

I'm going to think about any other that could be nice to have
